// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/json.ts";
import * as $3 from "./routes/go/[id].ts";
import * as $4 from "./routes/go/index.ts";
import * as $5 from "./routes/index.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/api/json.ts": $2,
    "./routes/go/[id].ts": $3,
    "./routes/go/index.ts": $4,
    "./routes/index.tsx": $5,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
